AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Max: 120

Lint/DuplicateBranch:
  IgnoreLiteralBranches: true
